argonne-lcf/dlio_benchmark

- src/dlio_benchmark.py
- src/utils/config.py
This PR fixes
1. `epochs_between_evals`, `enable_chunking`  parameters were not initialised from the config
2.  Currently, log file is missing in the final results as log file was getting deleted after it was initialised. Code is rearranged so that `os.remove` is moved to the top
> Add dlio fixes

- src/data_generator/data_generator.py
Number of folders for evaluation has to calculated based on `num_subfolders_eval`
> Fixing folder number for evaluation

- src/dlio_benchmark.py
- src/utils/statscounter.py
Fixing issue raised in https://github.com/argonne-lcf/dlio_benchmark/issues/15
> fixed checkpoint issues

- README.md
- configs/workload/bert.yaml
- configs/workload/cosmoflow.yaml
- configs/workload/default.yaml
- configs/workload/unet3d.yaml
- docs/source/config.rst
- docs/source/copyright.rst
- docs/source/examples.rst
- docs/source/knownissues.rst
- src/dlio_benchmark.py
- src/framework/tf_framework.py
- src/profiler/tf_profiler.py
- src/reader/reader_handler.py
- src/reader/tf_data_loader_reader.py
- src/reader/tf_reader.py
- src/reader/torch_data_loader_reader.py
- src/utils/config.py
- tests/dlio_benchmark_test.py
In this PR, I changed the configuration 
1. read_shuffle -> file_shuffle: shuffling among the file list
2. memory_shuffle -> sample_shuffle: shuffle among the samples 
3. batch_size is now moved to the reader group since it is a reader property instead of the dataset
The YAML files are changed also.
> Minor modification of configuration options to remove some confusion

- src/data_loader/base_data_loader.py
- src/data_loader/data_loader_factory.py
- src/data_loader/tf_data_loader.py
- src/data_loader/torch_data_loader.py
- src/dlio_benchmark.py
- src/framework/tf_framework.py
- src/framework/torch_framework.py
- src/reader/csv_reader.py
- src/reader/hdf5_reader.py
- src/reader/jpeg_reader.py
- src/reader/npz_reader.py
- src/reader/png_reader.py
- src/reader/reader_handler.py
- src/reader/tf_reader.py
- src/storage/file_storage.py
- src/storage/s3_storage.py
- src/utils/config.py
- src/utils/utility.py
- tests/dlio_benchmark_test.py
Merged https://github.com/argonne-lcf/dlio_benchmark/pull/48
Added sleep time for preprocessing.
> Improved tracing utility added preprocessing support

- src/data_loader/base_data_loader.py
- src/data_loader/data_loader_factory.py
- src/data_loader/tf_data_loader.py
- src/data_loader/torch_data_loader.py
- src/dlio_benchmark.py
- src/framework/tf_framework.py
- src/framework/torch_framework.py
- src/reader/csv_reader.py
- src/reader/hdf5_reader.py
- src/reader/jpeg_reader.py
- src/reader/npz_reader.py
- src/reader/png_reader.py
- src/reader/reader_handler.py
- src/reader/tf_reader.py
- src/storage/file_storage.py
- src/storage/s3_storage.py
- src/utils/config.py
- src/utils/utility.py
- tests/dlio_benchmark_test.py
- Added logging to all functions.
- categories are correctly set so that they can be filtered.
- format of JSON is corrected.
- Additional args to events of internal profile to support filtering. 
- step_number, epoch_number, image_global_index, image_size
> Trace improvement.

- .github/workflows/python-package-conda.yml
- docs/source/config.rst
- src/common/constants.py
- src/data_generator/csv_generator.py
- src/data_generator/hdf5_generator.py
- src/data_generator/jpeg_generator.py
- src/data_generator/npz_generator.py
- src/data_generator/png_generator.py
- src/data_generator/tf_generator.py
- src/data_loader/tf_data_loader.py
- src/data_loader/torch_data_loader.py
- src/dlio_benchmark.py
- src/framework/tf_framework.py
- src/framework/torch_framework.py
- src/reader/csv_reader.py
- src/reader/hdf5_reader.py
- src/reader/jpeg_reader.py
- src/reader/npz_reader.py
- src/reader/png_reader.py
- src/reader/reader_handler.py
- src/reader/tf_reader.py
- src/storage/file_storage.py
- src/storage/s3_storage.py
- src/utils/config.py
- src/utils/utility.py
- tests/dlio_benchmark_test.py
This is to reduce the overhead for reader inititialization.
> Moved resize image to config

- .github/workflows/python-package-conda.yml
- .gitignore
- src/common/enumerations.py
- src/dlio_benchmark.py
- src/utils/utility.py
we have an internal profiler that traces python functions and lower level posix and studio calls.
> DLIO profiler integration

- .github/workflows/python-package-conda.yml
- src/dlio_benchmark.py
- src/reader/reader_handler.py
- src/utils/statscounter.py
- tests/dlio_benchmark_test.py
This PR contains minor changes: 
* Fixed bugs for training on a subset of files
* moved the position of start and end timers to more appropriate places.
> Mlperf storage v0.5.1

- dlio_benchmark/data_loader/torch_data_loader.py
On lassen we use 1.3.1 which showed this bug.
> Update typo which gives issue for pytorch 1.3.1

- Dockerfile
> fix Docker file to use venv. 

- .github/workflows/python-package-conda.yml
> Added force install for profiler for avoiding caching issues

- .github/workflows/python-package-conda.yml
- .readthedocs.yaml
- tests/dlio_benchmark_test.py
The total time for running github tests is getting long. This PR reduces the computation time, num_files in the tests, to reduce the overall time for testing.
> Reducing Github actions time

- dlio_benchmark/main.py
- dlio_benchmark/utils/utility.py
- tests/dlio_benchmark_test.py
Current we only initialize but never finalize. This throws an MPI Abort with some new versions of openmpi.
> Fix MPI finalization.

- requirements.txt
Requirements added as in https://github.com/argonne-lcf/dlio_benchmark/blob/main/setup.py#L15
> Adding dlio_profiler to requirements.txt

- dlio_benchmark/main.py
Currently we reinitialize dataloader on every epoch.
so the recommended way to use Pytorch data loader is
initialize data loader
iterate on epoch
iterate on batches
train
What we are doing is
iterate on epoch
initialize data loader
iterate on batches
train
> Fix dataloader initialization to only happen once. Not on every epoch.

- dlio_benchmark/configs/workload/resnet50_a100.yaml
- dlio_benchmark/configs/workload/resnet50_h100.yaml
- dlio_benchmark/configs/workload/resnet50_v100.yaml
- dlio_benchmark/utils/config.py
> fixed sample distribution bugs

- dlio_benchmark/utils/config.py
Removes the redundant calls to `os.path.abspath`
> Optimization to sample distribution

- .github/workflows/python-package-conda.yml
- dlio_benchmark/configs/workload/cosmoflow_a100.yaml
- dlio_benchmark/configs/workload/cosmoflow_h100.yaml
- dlio_benchmark/configs/workload/cosmoflow_v100.yaml
- dlio_benchmark/configs/workload/resnet50_a100.yaml
- dlio_benchmark/configs/workload/resnet50_h100.yaml
- dlio_benchmark/configs/workload/resnet50_v100.yaml
Because of the issue with DALI data loader. We change the default data loader to tensorflow for resnet50 and cosmoflow workload.
> Changed from PyTorch to Tensorflow for ResNet50 and CosmoFlow

- .github/workflows/python-package-conda.yml
@hariharan-devarajan please review
> DFTracer CI environment variables fixed.

- pyproject.toml
- setup.py
> Refactor `setup.py` to Enable PyPI Publishing

- dlio_benchmark/utils/utility.py
The current mocking was not following the correct signature as used in DFTracer
> Fixed mocking for DFTracer

- .github/workflows/cd.yml
- setup.py
> Fix PyPI Publish Issue and Improve Project Metadata

- dlio_benchmark/data_generator/hdf5_generator.py
The import of math is needed for HDF5 chunking.
> Fix missing import for chunking.

- .github/workflows/jekyll-gh-pages.yml
- dlio_benchmark/checkpointing/base_checkpointing.py
- dlio_benchmark/checkpointing/pytorch_checkpointing.py
- dlio_benchmark/checkpointing/tf_checkpointing.py
- dlio_benchmark/main.py
- dlio_benchmark/utils/config.py
- dlio_benchmark/utils/statscounter.py
This is just to fix some left over logging.debug, logging.info after merging. 
I also removed the doc deployment which is causing failure. We already make the deployment through readthedoc.
> left over logging fix

- .github/workflows/docker.yml
addresses #244
docker fix in #265
> ci: add docker build and publish

- .github/workflows/ci.yml
- dlio_benchmark/checkpointing/base_checkpointing.py
- dlio_benchmark/common/enumerations.py
- dlio_benchmark/configs/workload/llama_1t.yaml
- dlio_benchmark/configs/workload/llama_405b.yaml
- dlio_benchmark/configs/workload/llama_70b.yaml
- dlio_benchmark/configs/workload/llama_70b_zero3.yaml
- dlio_benchmark/configs/workload/llama_7b.yaml
- dlio_benchmark/configs/workload/llama_7b_zero3.yaml
- dlio_benchmark/configs/workload/llama_8b_zero3.yaml
- dlio_benchmark/main.py
- dlio_benchmark/utils/config.py
- dlio_benchmark/utils/statscounter.py
- docs/source/config.rst
- requirements.txt
- setup.py
> Enhancement for checkpoint feature

- .github/workflows/ci.yml
- dlio_benchmark/reader/npy_reader_odirect.py
- dlio_benchmark/reader/npz_reader_odirect.py
- dlio_benchmark/reader/reader_factory.py
- dlio_benchmark/utils/config.py
- docs/source/config.rst
Reorganized the code provided by YardenMa from PR https://github.com/argonne-lcf/dlio_benchmark/pull/250 to follow the recommentations in https://github.com/argonne-lcf/dlio_benchmark/pull/250#pullrequestreview-2662717496.
> Reorganized the code provided by YardenMa for O_DIRECT support with NPY and NPZ formats and pytorch

- .github/workflows/ci.yml
- dlio_benchmark/checkpointing/base_checkpointing.py
- dlio_benchmark/checkpointing/pytorch_checkpointing.py
- dlio_benchmark/checkpointing/tf_checkpointing.py
- dlio_benchmark/utils/config.py
- docs/source/config.rst
- tests/dlio_benchmark_test.py
This PR merges both #281 and #282 into a single one.
> RAM optimisations for checkpointing

- dlio_benchmark/utils/statscounter.py
- dlio_benchmark/utils/utility.py
This is to support the case where different hosts will have different number of processes.
> Support for inhomogeneous setup 

- dlio_benchmark/utils/statscounter.py
- dlio_benchmark/utils/utility.py
To address https://github.com/mlcommons/storage/issues/157
> added support for inhomogeneous setup (#298)
