- .gitignore
- README.md
- configs/workload/bert_test.yaml
- configs/workload/unet3d.yaml
- configs/workload/unet3d_test.yaml
- src/dlio_postprocessor.py
- src/framework/tf_framework.py
- src/profiler/iostat_profiler.py
- src/profiler/no_profiler.py
- src/utils/config.py
- src/utils/utility.py
Touch up README 
- fix typos, add details for report generation, tell user to flush caches between datagen and run.
Change default UNET3D and BERT params 
- I think we shouldn't encourage running datagen and run right after since the report generated will be wrong due to not flushing the caches. 
- Some of the parameter values were wrong e.g. file size for UNET3D
Fix iostat running 
- Add parameter to specify which io devices to trace 
- Change logging time to local time, to match with iostat (though this might not work on all machines depending on the time config)
- Since we're trying to remain general, you may not want to run iostat all the time? I dont know.
Add test configs for bert and unet that finish quickly to test the end-to-end process.
ISSUES:
- The BERT workload should …
> Some fixes 

- docs/source/config.rst
- requirements.txt
- src/data_generator/hdf5_generator.py
- src/data_generator/jpeg_generator.py
- src/data_generator/png_generator.py
- src/dlio_benchmark.py
- src/framework/framework.py
- src/framework/tf_framework.py
- src/framework/torch_framework.py
- src/profiler/darshan_profiler.py
- src/profiler/io_profiler.py
- src/reader/torch_data_loader_reader.py
- src/utils/config.py
In this PR, I fixed the following issues: 
* Fixed the checkpointing issue raised by: https://github.com/argonne-lcf/dlio_benchmark/issues/12. I also changed the default values for ```steps_between_checkpoints``` and ```epochs_between_checkpoints```
* fixed environment setup for Darshan profiler to reflect the recent changes in darshan. I removed darshan_preload config option since the darshan runtime library has to be loaded before python in LD_PRELOAD. 
Besides, there are also following minor fixes
* Removed logdir from the config options, since it is no longer needed
* fixed bugs caused in png generator due to dtype issue. 
* fixed bugs in HDF5 generator
* fixed issues in requirement.txt (unfound *+cpu packages)
> Fixed issues related to checkpointing and profiling

- .github/workflows/python-package-conda.yml
- src/data_generator/tf_generator.py
- src/dlio_benchmark.py
- src/reader/torch_data_loader_reader.py
- src/utils/statscounter.py
- tests/dlio_benchmark_test.py
I added the following tests in tests/dlio_benchmark_test.py
* testing the data generation for different formats
* testing full benchmarks for different formats
* testing checkpointing (for both epochs_between_checkpoints and steps_between_checkpoints)
Two pytest tests are included in the GitHub action. 
I also fixed the issues for reading png and jpeg files with torch data loader.
> Adding PR unit tests for testing different data format and fixing issues for reading png and jpeg with pytorch data folder. 

- .gitignore
- configs/workload/unet3d.yaml
- src/reader/hdf5_stimulate.py
- src/utils/config.py
- Add checkpointing after every eval for UNET3D
- Remove old prefetch param & align hdf5_stimulate (btw, should it be called simulate?) that was the only one still using it
- add checkpoints folder to gitignore
> Add ckpting to UNET3D workload, remove old prefetch param

- .github/workflows/python-package-conda.yml
- configs/workload/bert.yaml
- configs/workload/cosmoflow.yaml
- configs/workload/default.yaml
- configs/workload/unet3d.yaml
- docs/source/config.rst
- docs/source/examples.rst
- requirements.txt
- src/common/enumerations.py
- src/data_generator/csv_generator.py
- src/data_generator/data_generator.py
- src/data_generator/hdf5_generator.py
- src/data_generator/jpeg_generator.py
- src/data_generator/npz_generator.py
- src/data_generator/png_generator.py
- src/data_generator/tf_generator.py
- src/dlio_benchmark.py
- src/framework/framework.py
- src/framework/tf_framework.py
- src/framework/torch_framework.py
- src/reader/reader_handler.py
- src/storage/file_storage.py
- src/storage/s3_storage.py
- src/storage/storage_factory.py
- src/storage/storage_handler.py
- src/utils/config.py
- tests/dlio_benchmark_test.py
This PR adds Storage interface in DLIO. This adds support for multiple storage backends like S3 objects etc 
**There is no change in current DLIO functionality or  behaviour with this PR** 
This PR adds
1. Adds one new config parameter in Dataset- `storage_type`. The default is `local_fs`.  The other option is `S3`
2. New Storage Interface is created for all filesystem operations 
3. For any benchmark, data dir and checkpoint dir has to be created on the storage system under test. While output folder is stored on the local client system itself.  So,  for all operations on data_dir and checkpoint_dir uses storage system interface.
4. Currently used local file system calls(using os module) are moved to file_storage.py. S3 apis are implemented in s3_storage.py
5. Changes are made only to TF …
> Adding Storage interface for supporting multiple storage backends

- src/data_generator/tf_generator.py
- src/reader/csv_reader.py
- src/reader/hdf5_reader.py
- src/reader/hdf5_stimulate.py
- src/reader/npz_reader.py
- src/reader/reader_handler.py
- src/utils/config.py
This PR has
1. Some replacements for `read_shuffle`  to `file shuffle` and `memory_shuffle`  to `sample_shuffle` were missing.
2.  eval_after_epoch is initialised to 1 as epoch 0 is invalid. `checkpoint_after_epoch` is already set to 1. 
3. In `tf_generator`, every sample is randomised.
@jovonho @zhenghh04
> Code Fixes

- configs/workload/unet3d.yaml
- src/reader/torch_data_loader_reader.py
- Added the measured sleep time for V100-32GB batch size 4
- Removed evaluation from the UNET3D config
- fix random bug
PS: Did we say we want the base dataset to be 300GB instead of the current 30GB?
> Add the UNET3D sleep time for V100 32GB batch size 4

- configs/workload/bert.yaml
- configs/workload/unet3d.yaml
Minor config changes are added 
1. Two space indentation is added in `bert.yaml `to be consistent with other workloads
2. `file_prefix` is added to `bert` workload file generation. (Default was `img`)
3. `file_shuffle` and `sample_shuffle` is set to `seed` for both `bert` and `unet3d`
4. `checkpoint_folder` location is added to both `bert` and `unet3d`
5. `keep_files` is removed as it is set to true by default
> Minor config changes

- src/reader/reader_handler.py
Fixed #50 
The samples are randomized and the files are randomized. But the file_index assigned to the thread is in order. This allows us to free the files once they are fully read.
> bug fix to free memory once file is completely read

- .github/workflows/python-package-conda.yml
- src/common/constants.py
- src/data_loader/tf_data_loader.py
- src/data_loader/torch_data_loader.py
- src/dlio_benchmark.py
- src/framework/tf_framework.py
- src/framework/torch_framework.py
- src/reader/csv_reader.py
- src/reader/hdf5_reader.py
- src/reader/jpeg_reader.py
- src/reader/npz_reader.py
- src/reader/png_reader.py
- src/reader/reader_handler.py
- src/reader/tf_reader.py
- src/storage/file_storage.py
- src/storage/s3_storage.py
- src/utils/config.py
- src/utils/utility.py
- tests/dlio_benchmark_test.py
Instead of 
```
global profile_args
profile_args["epoch"] = epoch_number
t0 = time()
super().__init__(format_type, dataset_type, epoch_number)
self._dataset = None
t1 = time()
PerfTrace.get_instance().event_complete(f"{self.__init__.__qualname__}", MY_MODULE, t0, t1 - t0,
arguments=profile_args)
```
We do just this
```
with Profile(name=f"{self.__init__.__qualname__}", cat=MODULE_DATA_LOADER, epoch=epoch_number):
super().__init__(format_type, dataset_type, epoch_number)
self._dataset = None
```
> instead of using direct methods using enter and exit.

- dlio_benchmark/utils/config.py
Check to see if number of cores available to process are enough for read threads. Closes #69
> Added validation to check enough core available for reading

- dlio_benchmark/data_loader/dali_data_loader.py
Fixes #90 
Output of 
with prefetch size 1
```dlio_benchmark workload=unet3d ++workload.reader.data_loader=dali ++workload.train.epochs=2 ++workload.workflow.train=True ++workload.dataset.num_files_train=16 ++workload.dataset.num_files_eval=16 ++workload.reader.read_threads=4 ++workload.reader.prefetch_size=1 ++workload.reader.batch_size=1```
and with prefetch size 4
`dlio_benchmark workload=unet3d ++workload.reader.data_loader=dali ++workload.train.epochs=2 ++workload.workflow.train=True ++workload.dataset.num_files_train=16 ++workload.dataset.num_files_eval=16 ++workload.reader.read_threads=4 ++workload.reader.prefetch_size=4 ++workload.reader.batch_size=1`
> Fixed dali data loader execution.

- dlio_benchmark/utils/utility.py
We do not need [ or ] calls as DLIO Profiler adds them on finalize.
Additionally, adding info logging to show if DLIO Profiler is used or not.
> Added Info logging for profiler and removed unnecessary bracket calls.

- dlio_benchmark/main.py
So we pass absolute path to profiler but we pass relative to code itself.
> Fix the data dir path

- .readthedocs.yaml
The simple PR fixed the build issue found in readthedoc
> fixed readthedoc build issue

- setup.py
PyPI now hosts the source of dip_profiler_py at https://files.pythonhosted.org/packages/ac/b0/6ed842fd785ce692268b92461e6348b39fe9dca5d9ebea725d7d54edfa3b/dlio_profiler_py-0.0.2.tar.gz and can be directly used instead of the GitHub link. GitHub link would be only needed if we need the dev version of dlio_profiler
> Switch dlio_profiler to use pypi instead of github

- dlio_benchmark/framework/torch_framework.py
Checkpoint folders and files are to be created relative to the storage_root of the storage class used for the run.  Code in torch_framework.py for checkpoint_folder and checkpoint file creation is hard-coded using posix calls which may not be appropriate for future storage classes, and the checkpoint_folder is not relative to the storage_root.  The checkpoint() method has been changed to use storage class methods.
> torch checkpoint creation should use storage class methods

- dlio_benchmark/main.py
Remove get_storage() and create_namespace() calls that were used to create output_folder, those calls only work if the storage class happens to be posix.  If the class is S3, then storage_root is a bucket and create_namespace() is a no-op, so the output_folder directory does not get created.  Since the logs are all posix-based, use os.makedirs() to create output_folder. Also move the basicConfig() call to the point after where the previous dlio.log file has been deleted so that log messages don't go to an unlinked file.  Move a message that was issued before the prior log was deleted to a spot after where the new log has been configured.
> Create output_folder using os.makedirs()

- dlio_benchmark/data_loader/torch_data_loader.py
- dlio_benchmark/main.py
- dlio_benchmark/utils/config.py
When reader_threads child processes are started with multiprocessing_context set to either spawn or forkserver, the new child processes do not have the dlio.log file open any longer.  Change worker_init() to reopen the dlio.log file in those cases. When the context is set to fork, the dlio.log file remains open in the child process and does not have to be reopened.
> Reopen dlio.log in non-fork reader_threads child processes

- .github/workflows/python-package-conda.yml
- dlio_benchmark/data_loader/torch_data_loader.py
- dlio_benchmark/main.py
- dlio_benchmark/utils/config.py
- dlio_benchmark/utils/utility.py
- setup.py
Fixes #135 
Also moved the release of DLIO Profiler 0.0.3
> added dlp for spawned workers pytorch

- .github/workflows/python-package-conda.yml
- dlio_benchmark/data_loader/torch_data_loader.py
- dlio_benchmark/utils/config.py
So we had a feature for file shuffling and sample shuffling for iterative case.
This create unintended effect on index based approach.
For instance in the dataloader,
1. we are passing a random shuffler plus, we do our own shuffling. This results in cache misses for the dataloader.
2. Also, in our random shuffling, we need to set torch seed, a generator, and then pass that to random shuffler. Else result would be non-deterministics.
> Fix random sampling pytorch non-determinism.

- dlio_benchmark/data_loader/data_loader_factory.py
- dlio_benchmark/main.py
- dlio_benchmark/reader/reader_factory.py
- dlio_benchmark/utils/config.py
Currently, we print the dlp logger file even if DLIO is disabled. Also, we need to print only for rank 0—similar changes for all factories.
> Fixed printing for DLIO output.

- README.md
- docs/source/config.rst
- docs/source/index.rst
- docs/source/instructions_lassen.rst
- docs/source/run.rst
People get confused with profiler conf as most of it doesn't work. 
Doc fixes include
> Doc changes to fix DLIO profiler and remove IOStat

- dlio_benchmark/data_loader/torch_data_loader.py
- dlio_benchmark/utils/config.py
So we were not converting the string into enum, causing the issues and confusion for #149.
Additionally, the random sampler doesn't shard the data. Therefore, I wrote a custom sampler that will shard the dataset and ensure non-overlapping ranges for seeded randomness.
> Fix sample shuffling 

- dlio_benchmark/data_generator/indexed_binary_generator.py
The struct.pack() call in generate() in indexed_binary_generator.py caches the data that it produces, and apparently doesn't evict the cache, such that after 49 indexed_binary files have been created the kernel kills the process due to OOM.  This mod adds a call to struct._clearcache() after each data files is written to release the cached data, keeping the process memory size stable.
> generating indexed_binary files causes kernel OOM to kill process (#181)

- dlio_benchmark/reader/tf_reader.py
Instead of processing the elements one-by-one in the reader pipeline, we use a batch. 
After having applied this modification, perf shows that a couple of functions take less time. 
These function are, I believe , related to C function call switches and python interpreter:
EagerTensor_init took 12% of the time => now 0.26%
pybind11::cpp_function::dispatcher took 10% => now 0.64%
PyEval_EvalFrameDefault took 9% => now 0.19% 
On the same test system, it doubles the throughput of resnet50 (1x H100).
This throughput was also measured on the network:
Test | Throughput (MB/s) | AU (%) | # reader threads
-- | -- | -- | --
Without   patch, 1x H100 | 115.6499 | 59.3728 | 4
With   patch, 1x H100 | 193.4854 | 99.417 | 4
> Improve tfreader parsing performance (batch)

- dlio_benchmark/reader/tf_reader.py
Important: This is a draft and I haven't really verified that this change is correct. It could be wrong. 
Instead of sharding the files, we shard the filenames. 
I used the example described in the source code of tensorflow. 
https://github.com/tensorflow/tensorflow/blob/1c7f292617e7c276d03c51894928004625f8ec29/tensorflow/python/data/ops/dataset_ops.py#L1642
```python
d = Dataset.list_files(pattern, shuffle=False)
d = d.shard(num_workers, worker_index)
d = d.repeat(num_epochs)
d = d.shuffle(shuffle_buffer_size)
d = d.interleave(tf.data.TFRecordDataset,
cycle_length=num_readers, block_length=1)
d = d.map(parser_fn, num_parallel_calls=num_map_threads)
```
This mean that each MPI process only manage a random set of files, instead of a random set of images from all files.
This change remove …
> Shard filenames instead of images (tfreader)

- dlio_benchmark/utils/utility.py
* Request changes from MLPerf Storage (#199)
* added au metric to the configuration file; set shuffling and shuffle buffer size to be 2 for cosmoflow
* removed dependencies on dlioprofiler
* fixed bugs
* Fixed potential insufficient samples due to num_files is not divisible by comm.size (#200)
* added au metric to the configuration file; set shuffling and shuffle buffer size to be 2 for cosmoflow
* removed dependencies on dlioprofiler
* fixed bugs
* recovered back dlio_profiler
* fixed potential not enough samples
* Update tf_reader.py
* Mlperf requests (#201)
* added au metric to the configuration file; set shuffling and shuffle buffer size to be 2 for cosmoflow
* removed dependencies on dlioprofiler
* fixed bugs
* fixed issue with dlio_profiler
* bring back dlio_profiler_py
> sync up mlperf_storage_v1.0

- setup.py
Making it the latest as some dependencies mess up with Python >= 3.9
The Networkx package gets stuck as it cannot resolve the dependency for >= 3.9.
The following change to >= would help resolve all dependencies for Python.
> Adding version fix restricts matching on python 3.9 environment.

- .gitignore
- dlio_benchmark/main.py
- dlio_benchmark/utils/utility.py
So the main issue, is that we cannot simply initialize MPI in global scope as it will make the spawn multi-processing context in PyTorch fail.
This PR, fixes this by moving the initialization code to a function scope.
> Only intialize and finalize on DLIOMPI

- dlio_benchmark/data_loader/tf_data_loader.py
- dlio_benchmark/reader/tf_reader.py
- dlio_benchmark/utils/config.py
The sample building and native data loader case is needed only for DLIO created data loaders. For native data loaders which provide their own API;s they provide their own indexing and there this sampling can be ignored.
> Ignore file indexing for native data loader.

- dlio_benchmark/data_loader/dali_data_loader.py
- dlio_benchmark/data_loader/torch_data_loader.py
- dlio_benchmark/main.py
- dlio_benchmark/reader/indexed_binary_mmap_reader.py
- dlio_benchmark/reader/indexed_binary_reader.py
- dlio_benchmark/reader/reader_handler.py
- dlio_benchmark/reader/tf_reader.py
- dlio_benchmark/utils/config.py
- dlio_benchmark/utils/utility.py
- we fix reconfiguration logic to build rank map for train and valid.
- Now we need reconfigure per epoch to shuffle the list.
> Fixed iterator to only store data for that rank.

- .github/workflows/ci.yml
- dlio_benchmark/data_generator/hdf5_generator.py
- tests/dlio_benchmark_test.py
1. Improve generation of hdf5 files it was taking too long.
2. Do not finalize in pytest this allows multiple tests to run together.
> Improve CI Performance.

- dlio_benchmark/data_generator/hdf5_generator.py
The current message says `Generating NPZ data` when it should say `Generating HDF5 data`. 
This can be misleading for users.
> fix misleading generator message

- dlio_benchmark/main.py
Due to the nature of normal random equation, the value generated can be negative.
Enforcing it to be positive using `abs` will fix the issue.
Fix: #232
> fix negative value of computation time when stdev exists

- dlio_benchmark/configs/workload/megatron_deepspeed.yaml
- dlio_benchmark/data_generator/indexed_binary_generator.py
- dlio_benchmark/reader/indexed_binary_mmap_reader.py
The type is wrong and should be uint64.
> Bugfix: fix type of number for offset and size

- docs/source/config.rst
The documentation says use `chunking` for HDF5 data creation but the code uses `enable_chunking`
> Fix wrong configuration for hdf5 chunking

- dlio_benchmark/data_loader/dali_data_loader.py
- dlio_benchmark/data_loader/native_dali_data_loader.py
- dlio_benchmark/main.py
If we have 730 steps, DLIO benchmark only executes until 729
The bug also persists when user specified `total_training_steps`
Fix: #235
> fix last step is not executed

- dlio_benchmark/data_loader/native_dali_data_loader.py
- dlio_benchmark/data_loader/tf_data_loader.py
- dlio_benchmark/data_loader/torch_data_loader.py
- dlio_benchmark/main.py
If we use `dlp.iter` inside `main.py`, this does not reflect the real fetch data since the data is already fetched inside `DataLoader.next()`. Because of this, we ended up tracing the fetching of batch data that resides in the memory instead of tracing its fetching duration from filesystem or other sources.
This PR addresses the problem where we put `dlp.iter` inside the dataloader, as close as possible to the dataset itself.
For dali dataloader, I haven't implemented the fix since there is no visible iteration there (DALI uses `share_outputs`)
Note: @hariharan-devarajan when we bump the dftracer version, we should provide the name of the `dlp.iter`.
I left a note to change `dlp.iter` to `dlp.iter(..., name=self.next.__qualname__)`
> fix wrong tracing location of fetch data

- dlio_benchmark/data_loader/torch_data_loader.py
- dlio_benchmark/utils/config.py
- docs/source/config.rst
This PR gives us option to disable pin memory in pytorch dataloader.
I encountered error while emulating stormer when we increase the prefetch factor since the memory is being reserved and cannot be released until the dataloader is finished.
Also, pin_memory is beneficial for GPU memory pinning which we do not use at all for DLIO [1, 2]
I set the default to True for backward compatibility, let me know if I should put `pin_memory=False` as default in the configuration.
Reference:
[1] https://pytorch.org/tutorials/intermediate/pinmem_nonblock.html
[2] https://discuss.pytorch.org/t/when-to-set-pin-memory-to-true/19723/19
> enable option to disable pin_memory in pytorch

- dlio_benchmark/reader/reader_handler.py
This PR addresses the problem where `random.normal` result can be negative.
if we do `max(t, 0)` then we will reduce the variance of preprocess time when the generated value is negative. 
It is better to use `abs` in this case.
At the same time, I add strict comparison to make sure user does not give negative value while specifying `preprocess_time` or `preprocess_time_stdev` in the config.
> Change `max` to `abs` for preprocess time

- .github/workflows/ci.yml
- dlio_benchmark/checkpointing/base_checkpointing.py
- dlio_benchmark/configs/workload/megatron_deepspeed.yaml
- dlio_benchmark/data_generator/indexed_binary_generator.py
- dlio_benchmark/reader/indexed_binary_mmap_reader.py
- tests/dlio_benchmark_test.py
The logic is as follows now. 
Assume we have 40 layers with tensor parallelism of 4 and pipeline parallelism of 8
Then, the checkpointing would have 44 layers (40 + 4 tensor pipeline layers) spread across every 32 ranks.
So, given pipeline_rank being every four ranks in this case, rank 0-3 is pipeline rank 0, 4-7 is pipeline rank 1, and so on.
Then, I expect a layer distribution among each pipeline rank to be
(pipeline_rank, start_layer_index, end_layer_index) both the start and end are inclusive.
(0, 0, 5)
(1, 6, 11)
(2, 12, 17)
(3, 18, 23)
(4, 24, 28)
(5, 29, 33)
(6, 34, 38)
(7, 39, 43)
Also, a tensor parallelism of 4 would mean each layer tensor would be divided by four on each rank.
So if a layer was (1MB, 1GB) tensors
They would be stored as 256KB, 256MB tensors by each rank.
> New improved modelling for LLM Deepspeed.

- .github/workflows/ci.yml
- dlio_benchmark/framework/framework.py
- dlio_benchmark/framework/tf_framework.py
- dlio_benchmark/framework/torch_framework.py
- dlio_benchmark/main.py
- dlio_benchmark/reader/dali_image_reader.py
- dlio_benchmark/reader/dali_npy_reader.py
- dlio_benchmark/reader/dali_tfrecord_reader.py
- dlio_benchmark/reader/reader_handler.py
- dlio_benchmark/utils/config.py
- dlio_benchmark/utils/utility.py
- docs/source/config.rst
- tests/dlio_benchmark_test.py
This PR adds options for users to specify the type of distribution for time metrics. This is useful when computation time, preprocessing time, or evaluation time doesn’t follow a normal distribution.
The existing API (`_time` and `_time_stdev`) is fully compatible, so no changes are needed in the configuration – it will default to assuming a normal distribution.
The configuration can be specified as nested yaml as follow
```yaml
computation_time:
mean: 1.0
stdev: 0.1
type: normal
computation_time:
mean: 1.0
computation_time:
mean: 1.0
stdev: 0.1
computation_time: 1.0
computation_time_stdev: 0.1
computation_time: 1.0
computation_time:
min: 0.5
max: 1.5
type: uniform
computation_time:
shape: 1.0
scale: 1.0
type: gamma
computation_time:
scale: 1.0 …
```
> Add user config to specify type of distribution of time configuration

- .github/workflows/jekyll-gh-pages.yml
This is to fixed the issue for recent requirement on deploying documentation. Without this fix, the github actions are failing.
> fixed bug on doc action

- dlio_benchmark/main.py
- requirements.txt
- setup.py
- tests/conftest.py
- tests/dlio_benchmark_test.py
This PR will update pydftracer package from `1.0.2` to `1.0.6`.
Note that pydftracer package `1.0.6` still does not include the new API of `dlp.iter(self, func, name, iter_name)` that is needed for [torch data loader](https://github.com/argonne-lcf/dlio_benchmark/blob/main/dlio_benchmark/data_loader/torch_data_loader.py#L169) but it is not a big of a deal for now.
Thanks!
> upgrade pydftracer package

- dlio_benchmark/checkpointing/checkpointing_factory.py
- dlio_benchmark/common/enumerations.py
- dlio_benchmark/data_generator/data_generator.py
- dlio_benchmark/data_generator/indexed_binary_generator.py
- dlio_benchmark/data_generator/jpeg_generator.py
- dlio_benchmark/data_generator/png_generator.py
- dlio_benchmark/data_generator/synthetic_generator.py
- dlio_benchmark/data_loader/base_data_loader.py
- dlio_benchmark/data_loader/dali_data_loader.py
- dlio_benchmark/data_loader/data_loader_factory.py
- dlio_benchmark/data_loader/native_dali_data_loader.py
- dlio_benchmark/data_loader/synthetic_data_loader.py
- dlio_benchmark/data_loader/tf_data_loader.py
- dlio_benchmark/data_loader/torch_data_loader.py
- dlio_benchmark/main.py
- dlio_benchmark/reader/dali_image_reader.py
- dlio_benchmark/reader/dali_npy_reader.py
- dlio_benchmark/reader/dali_tfrecord_reader.py
- dlio_benchmark/reader/image_reader.py
- dlio_benchmark/reader/indexed_binary_reader.py
- dlio_benchmark/reader/reader_factory.py
- dlio_benchmark/reader/reader_handler.py
- dlio_benchmark/reader/tf_reader.py
- dlio_benchmark/utils/config.py
- dlio_benchmark/utils/statscounter.py
- dlio_benchmark/utils/utility.py
- docs/source/config.rst
- docs/source/examples.rst
- docs/source/profiling.rst
In this PR, we changed the per step output from info to debug to reduce the logging overhead. 
We added support for changing logging level through environment variable `DLIO_LOG_LEVEL` which can be set to be error, warning, output, info, debug. By default we set as output. 
All the per-step log is put >= info level. The output level only contains per epoch logs. With this, the log file size is significantly reduced. 
In the debug level, the log format contains source file and line number, while other levels do not.
> Support for setting different DLIO_LOG_LEVEL

- Dockerfile
this also fixes docker build break with nvidia dali and fixes #243
[README.md](https://github.com/argonne-lcf/dlio_benchmark/blob/main/README.md#bare-metal-installation) says:
```
git clone https://github.com/argonne-lcf/dlio_benchmark
cd dlio_benchmark/
pip install .
dlio_benchmark ++workload.workflow.generate_data=True
```
also [ci.yml](https://github.com/argonne-lcf/dlio_benchmark/blob/main/.github/workflows/ci.yml#L65) doing
```
- name: Install DLIO via setup.py
if: matrix.venv == 'via-setup' && steps.cache-modules.outputs.cache-hit != 'true'
run: |
echo "venv: ${VENV_PATH} - gcc: $CC"
python -m venv ${VENV_PATH}
source ${VENV_PATH}/bin/activate
pip install --upgrade pip
pip install .[test]
```
> docker: use pip install to match readme

- dlio_benchmark/utils/statscounter.py
The saving checkpoint throughput is not written in the output.
```bash
[OUTPUT] 2025-03-19T08:07:38.517824 Running DLIO [Checkpointing] with 1 process(es)
[OUTPUT] 2025-03-19T08:08:03.667616 Starting block 1
[OUTPUT] 2025-03-19T08:08:08.668186 Starting saving checkpoint 1 after total step 1 for epoch 1
[OUTPUT] 2025-03-19T08:10:43.522289 Starting block 2
[OUTPUT] 2025-03-19T08:10:48.522737 Starting saving checkpoint 2 after total step 2 for epoch 1
[OUTPUT] 2025-03-19T08:13:21.650821 Starting loading checkpoint 2 after total step 2 for epoch 1
[OUTPUT] 2025-03-19T08:16:29.693366 Finished loading checkpoint 2 for epoch 1 in 341.1706 s; Throughput: 0.2575 GB/s
[OUTPUT] 2025-03-19T08:16:29.699832 Starting block 3
```
This patch match the print that is used for loading checkpoint. 
```bash …
```
> Fix saving checkpoint print

- README.md
- missing pull command for docker
- use python console scripts like in other examples instead of invoking python on script directly
> docs: small readme typo

- dlio_benchmark/utils/statscounter.py
The start checkpoint timer was not corrected set. It was set to checkpoint save state. This is included in #274
> Fixed loading checkpoint timer

- dlio_benchmark/configs/workload/dlrm.yaml
- dlio_benchmark/configs/workload/megatron_deepspeed_LLNL.yaml
- dlio_benchmark/data_generator/indexed_binary_generator.py
- dlio_benchmark/main.py
- dlio_benchmark/utils/config.py
- setup.py
Changes required to support CI support on HPC systems. I am building a CI on LC systems. This needs the following capabilities
> Refactor: move pydftracer dependency to extras for better management

- dlio_benchmark/main.py
- dlio_benchmark/utils/config.py
1. end_block is not called for checkpoint enabled workloads(eg: unet3d) . Stats are currently wrong (Ref commit: https://github.com/argonne-lcf/dlio_benchmark/pull/253/files#diff-763f5c93c1c2ccf78bad4c6555e3465b457c7546d76b1a0815a1f0a1a29c2365) 
2. std_dev is not used in the current installation and hence generated file sizes are wrong.
> Fixes for v2.0 benchmark

- .github/workflows/ci.yml
- dlio_benchmark/checkpointing/base_checkpointing.py
- dlio_benchmark/checkpointing/pytorch_checkpointing.py
- dlio_benchmark/checkpointing/tf_checkpointing.py
- dlio_benchmark/utils/config.py
- docs/source/config.rst
- tests/dlio_benchmark_test.py
Addresses Russ's discussion on using tensors filled with ones for checkpointing for MLPerf storage.
This PR changes the default behavior to use randomized tensor data for checkpoints.
To revert to tensors filled with ones, use the Hydra override:
`++workload.checkpoint.randomize_tensor=false`
The PR hasn't been tested yet.
> Randomize tensor data by default (checkpoint)
